services:
  backend:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    

  celery:
    image: celery:latest
    volumes:
      - .:/app
    depends_on:
      - backend
      - rabbitmq
      - redis
    command: celery -A subscription worker --loglevel=info


  redis:
    image: redis:latest
    ports:
      - 6378:6379

  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

    ports:
      - 5672:5672
      - 15672:15672

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    depends_on:
      - backend
      - celery
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555

  

networks:
  subscription:
    driver: bridge
